apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-runner
  namespace: gitea-runner
  labels:
    app: gitea-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea-runner
  template:
    metadata:
      labels:
        app: gitea-runner
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: gitea-runner
        image: gitea/act_runner:latest
        securityContext:
          privileged: true  # Required for Docker-in-Docker
        env:
        - name: GITEA_INSTANCE_URL     
          value: "http://gitea-service.gitea.svc.cluster.local:3000"
        - name: GITEA_RUNNER_REGISTRATION_TOKEN
          value: "os30pW4A2b4nwwAynRFrnjP9J7Q8CS0wqoKw6jIZ"  # Your new token
        - name: GITEA_RUNNER_NAME
          value: "gitea_runner"
        volumeMounts:
        - name: runner-home
          mountPath: /data
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: runner-home
        emptyDir: {}
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket