apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-runner
  namespace: gitea-runner
  labels:
    app: gitea-runner
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitea-runner
  template:
    metadata:
      labels:
        app: gitea-runner
    spec:
      serviceAccountName: my-service-account
      securityContext:
        fsGroup: 1000
      containers:
        - name: gitea-runner
          image: gitea/act_runner:latest
          securityContext:
            privileged: true
          env:
            - name: GITEA_INSTANCE_URL
              valueFrom:
                secretKeyRef:
                  name: gitea-runner-secret
                  key: INSTANCE_URL
            - name: GITEA_RUNNER_REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitea-runner-secret
                  key: REGISTRATION_TOKEN
            - name: GITEA_RUNNER_NAME
              valueFrom:
                secretKeyRef:
                  name: gitea-runner-secret
                  key: RUNNER_NAME
          volumeMounts:
            - name: runner-home
              mountPath: /data
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: runner-home
          emptyDir: {}
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
