apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea-ingress
  namespace: gitea
spec:
  rules:
    - host: gitea.local
      http:
        paths:
        - path: /
          pathType: Prefix          kubectl logs -n kube-system -l k8s-app=kube-dns
          backend:
            service:
              name: gitea-nodeport-service  # Fixed: Matches the actual Service name
              port:
                number: 3000  # Fixed: Matches the correct Service port
