apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: db
  labels:
    name: mysql-pv
spec:
  storageClassName: hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/c/yourDir/mysql"  # Update this path to a directory on your computer
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
