# Namespace: gitea-runner
apiVersion: v1
kind: Namespace
metadata:
  name: gitea-runner
---
# service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  namespace: gitea-runner
---
# role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-role
  namespace: gitea-runner
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
# rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-role-binding
  namespace: gitea-runner
subjects:
  - kind: ServiceAccount
    name: my-service-account
    namespace: gitea-runner
roleRef:
  kind: Role
  name: my-role
  apiGroup: rbac.authorization.k8s.io
